name: Checkin

on:
  schedule:
    # 9:00 am UTC+8
    - cron:  '0 1 * * *'
  workflow_dispatch:
    inputs:
      cookie:
        description: 'NJU Cookie'
        required: true

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Script (scheduled)
      id: run_scheduled
      if: ${{ github.event_name == 'schedule' }}
      run: |
        bash githubaction.sh
      env:
        NJU_COOKIE: ${{ secrets.NJU_COOKIE }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    - name: Run Script (manually)
      id: run_manually
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        bash githubaction.sh
      env:
        NJU_COOKIE: ${{ github.event.inputs.cookie }}
