name: cron

on:
  schedule:
    # 9:00 am UTC+8
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run Script
      run: |
        python checkin.py
      env:
        NJU_USER: ${{ secrets.NJU_USER }}
        NJU_PASS: ${{ secrets.NJU_PASS }}
