name: cron

on:
  schedule:
    # 9:00 am UTC+8
    - cron:  '0 1 * * *'
  workflow_dispatch:
    inputs:
      user:
        description: 'NJU ID'
        required: true
      pass:
        description: 'NJU Password'
        required: true

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Requirements
      run: |
        python -m pip install -r requirements.txt

    - name: Run Script (scheduled)
      if: ${{ github.event_name == 'schedule' }}
      run: |
        python checkin.py
      env:
        NJU_USER: ${{ secrets.NJU_USER }}
        NJU_PASS: ${{ secrets.NJU_PASS }}

    - name: Run Script (manually)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python checkin.py
      env:
        NJU_USER: ${{ github.event.inputs.user }}
        NJU_PASS: ${{ github.event.inputs.pass }}
